### ISSUE TITLE
NpcFlags forces to compile with wRobot 3.3.5 binaries

### ISSUE THREAD

**Issue by Schaka** [reapler/WoWDb-Manager#2]
I am currently writing a plugin to work cross-expansion. However, since the database is created with npcflags of TrinityCore 3.3.5, [this list](https://trinitycore.atlassian.net/wiki/spaces/tc/pages/74677606/creature+template335#creature_template335-npcflag) holds true within the database.

Unfortnately, compiling with the binaries for vanilla or TBC, flags have changed. The enum for 1.12 looks like this, for example:
`
None = 0,
    Gossip = 1,
    Questgiver = 2,
    CanSell = 4,
    Flightmaster = 8,
    CanTrain = 16,
    Spirithealer = 32,
    Innkeeper = 128,
    Auctioneer = 4096,
    CanRepair = 16384,
`

Instead, it would be great if we could just select based on a list of integers, rathern than having to rely on an expansion-specific enum within the wRobot binary.

**Comment by Schaka** [comment]
A current workaround is parsing a "magic" integer to an NPCFlags enum.

**Comment by jpramosi** [comment]
At first i'm sorry to answer really late and yes passing as int is a good workaround.
This version was initially developed for 3.3.5 but can be obvious used for lower versions.
I had planned to do a seperate version for 1.12 with a mangos based database (more precise values) but unfortunately i've got no time.
Thank you for noticing this.
